xarray-contrib/datatree

- datatree/datatree.py
- datatree/tests/test_dataset_api.py
Wrap all methods defined in the actual class definition of `Dataset` so they are mapped over entire subtree. For instance `.isel()`
> Expose dataset methods

- datatree/__init__.py
- datatree/io.py
Closes #6 using [BenBovy's code](https://gist.github.com/benbovy/92e7c76220af1aaa4b3a0b65374e233a)
No tests yet though.
> Open datatree

- datatree/datatree.py
Closes #18 using [this trick](https://github.com/TomNicholas/datatree/issues/18#issuecomment-904984392), although this approach will also need to be implemented for the other mixin's in PR's #10 and #17.
> Add API methods in class definition

- datatree/datatree.py
- datatree/tests/test_dataset_api.py
A WIP attempt to get operations like `*` and `+` working on `DatasetNode` objects.
Idea is to copy the pattern used to add these operators to `xarray.Dataset`, where `Dataset` inherits from `DatasetArithmetic`. 
`DatasetArithmetic` itself inherits from about 5 different Mixin classes, which I don't particularly want to regenerate, especially as `DatasetOpsMixin` is generated by templating in xarray. Here we instead just want to take the methods defined on `DatasetArithmetic` and decorate them with `map_over_subtree`, to get a `DataTreeArithmetic` object to inherit from.
Problem is at the moment I'm getting errors like this:
```
>       result = dt * dt
E       TypeError: unsupported operand type(s) for *: 'DatasetNode' and 'DatasetNode'
```
I don't understand why this is happening because …
> Expose dataset reduce operations

- datatree/datatree.py
- datatree/ops.py
- datatree/tests/test_dataset_api.py
Adds the operations defined in `xarray.core._typed_ops.py`, such as `__add__` and `__mul__`.
There is one test (for multiplication), but for reasons I don't understand it works when doing `dt * 5` but fails for `dt * dt`.
> [WIP] Add typed ops

- datatree/datatree.py
- datatree/tests/test_dataset_api.py
Close #36 via method (3): no longer wrap properties of a dataset, instead only being able to access them via the `.ds` attribute.
> Unexpose dataset properties

- datatree/datatree.py
- datatree/tests/test_datatree.py
Prevents the same node having both children and data variables with the same name, or at least prevents some of the possible ways this can occur (see #38).
> Name collisions

- README.md
- datatree/__init__.py
- datatree/datatree.py
- datatree/io.py
- datatree/mapping.py
- datatree/tests/test_dataset_api.py
- datatree/tests/test_datatree.py
- datatree/tests/test_mapping.py
- datatree/treenode.py
This PR reorganises the constructors for a `DataTree` object, so that `DataTree.__init__` now creates a single node (making the `DataNode` shortcut obselete), whilst creating an entire tree at once from a dictionary of `path: ds` pairs can still be done via a new `from_dict` classmethod.
This is much cleaner, and prevents the testing code being filled with `DataNode()` instead of `DataTree`, but it will also break most code relying on `datatree`.
@jhamman it looks like [ndpyramid](https://github.com/carbonplan/ndpyramid) points to this repo's `main` - do you want to freeze it so that I can make more changes like this without breaking your code? I'm about to experiment with changing other things too.
> Replace DataTree init method with from_dict

- datatree/datatree.py
- datatree/mapping.py
- datatree/tests/test_datatree.py
- datatree/tests/test_mapping.py
Originally I had the `.ds` attribute as being either an instance of `Dataset`, or `None` to represent no data. This isn't a good idea, so this PR changes it to instead use an empty Dataset to represent no data, so `.ds` can always be relied upon to return a `Dataset` object.
> Forbid .ds=None

- conftest.py
- datatree/__init__.py
- datatree/datatree.py
- datatree/formatting.py
- datatree/mapping.py
- datatree/testing.py
- datatree/tests/test_formatting.py
- datatree/tests/test_mapping.py
Adds assert functions and methods, fixing #27.
Includes an `assert_isomorphic` for when you want to assert that two trees have corresponding structures but don't want to check any of the data in the nodes.
I should add `assert_allclose` too, and still needs tests.
Once this works I will change all the existing tests to use `assert_identical`.
> Add assert_equal functions

- datatree/datatree.py
- datatree/io.py
- datatree/tests/test_datatree.py
This fixes a bug where the Zarr's consolidated metadata is computed after each group's write, rather than once at the end.
> fix bug where zarr's consolidated metadata is created after writing each group

- .github/workflows/main.yaml
> Remove lint workflow in favor of pre-commit.ci

- datatree/datatree.py
- datatree/formatting.py
- docs/source/quick-overview.rst
Makes `repr(dt)` consistent with `print(dt)`, like for xarray objects. Also means that you get the tree-like pretty representation by default when you display the object in ipython.
> Tree-like repr

- datatree/formatting.py
- datatree/tests/test_datatree.py
- datatree/tests/test_formatting.py
- docs/source/whats-new.rst
```python
In [1]: import xarray as xr
In [2]: import numpy as np
In [3]: from datatree import DataTree
In [4]: simpsons = DataTree.from_dict(
...:     {"/": xr.Dataset({"Age": np.NaN}),
...:      "Homer": xr.Dataset({"Age": 39}),
...:      "Homer/Bart": xr.Dataset({"Age": 10}),
...:      "Homer/Lisa": xr.Dataset({"Age": 8}),
...:      "Homer/Maggie": xr.Dataset({"Age": 1})},
...:      name="Abe",
...: )
```
displays as this
```
DataTree('Abe', parent=None)
│   Dimensions:  ()
│   Data variables:
│       Age      float64 nan
└── DataTree('Homer')
│   Dimensions:  ()
│   Data variables:
│       Age      int64 39
├── DataTree('Bart')
│       Dimensions:  ()
│       Data variables:
│           Age      int64 10
├── DataTree('Lisa')
│       Dimensions:  ()
│       Data variables:
│ …
```
> Str repr indentation

- datatree/io.py
- datatree/tests/test_io.py
The `with` context when opening the zarr group with result in calling
__exit__ on the store when the function completes. This calls `.close()`
on ZipStore's, which results in errors:
```
ValueError: Attempt to use ZIP archive that was already closed
```
> Do not call __exit__ on Zarr store when opening

- .github/workflows/main.yaml
- docs/source/installation.rst
This should have been done in #76 but I missed it.
> Remove anytree dependency from CI runs

- datatree/datatree.py
- datatree/tests/test_datatree.py
- docs/source/whats-new.rst
Adds a small check to prevent users from creating a node with a name that contains "/", which would mess up path-like access.
> Name checking

- datatree/formatting_html.py
- datatree/tests/test_formatting_html.py
- docs/source/whats-new.rst
Enable tree-style HTML representation.
(see #87 for a quick screenshot, produced by manually producing the HTML repr and dumping to file)
`black` shredded the indentation for the HTML stuff (lines 107 - 131 in formatting_html.py) -- if you want it back for readability, there are always tricks.
Achieved using roughly the following logic:
```mermaid
graph TD
datatree_repr --> node_repr
node_repr -->|via _obj_repr| summarize_children
summarize_children --> _wrap_repr
_wrap_repr --> node_repr
style summarize_children fill:#c60
style _wrap_repr fill:#0a0
```
Overall, this moves the padding logic out of `summarize_children` and into `_wrap_repr`.
* `_wrap_repr` is a new internal function that wraps the result from `node_repr`, or elsewhere, and adds some HTML wrapping.
* `summarize_children` …
> Enable tree-style HTML representation

- datatree/tests/conftest.py
- datatree/tests/test_dataset_api.py
- datatree/tests/test_datatree.py
- datatree/tests/test_formatting.py
- datatree/tests/test_io.py
- datatree/tests/test_mapping.py
- docs/source/whats-new.rst
Make `create_test_datatree` a fully fledged pytest fixture.
* `create_test_datatree` moved from `test_datatree.py` to folder level `conftest.py`, and converted to fixture.
* To use the fixture, add `create_test_datatree` to your test signature, then invoke it within your test.
* Added secondary utility fixture for ease, `simple_datatree` (also in folder level `conftest.py`).
* This is the result from calling `create_test_datatree()`
* As the fixture is initialized once per test module, this gives some performance benefits for test speed (the same pointer is thrown around).
* Accordingly, one should only use this fixture if no in place modifications are performed on the DataTree.
This makes it easier to add more unit tests. (I found that it was a bit tricky to find an example DataTree to …
> Make create_test_datatree a pytest.fixture

- datatree/datatree.py
- datatree/tests/test_datatree.py
- datatree/tests/test_treenode.py
- datatree/treenode.py
- docs/source/whats-new.rst
Fixes #112 (which was trivial), but then also fixes a bug I noticed with name permanence. This bug wasn't exposed because the name-related tests were testing `TreeNode` instead of `DataTree`, so I refactored until the existing tests correctly exposed the bug. Then I fixed the bug.
> Allow assigning Coercible values + NamedNode internal class

- datatree/datatree.py
- datatree/tests/test_datatree.py
- docs/source/api.rst
- docs/source/whats-new.rst
This adds a `pipe` method to `DataTree`, very similar to `Dataset.pipe` and `DataArray.pipe` (in fact, it is a modified copy).
> add `DataTree.pipe` to allow chaining `DataTree` consuming functions

- datatree/datatree.py
- datatree/tests/test_datatree.py
- docs/source/whats-new.rst
The docstring of `DataTree.from_dict` claims that it allows having `DataTree` objects as values, but both the type hints and the code disagree (the code fails because `DataTree(DataTree())` does not work).
The implementation I chose in this PR is to special-case `DataTree` objects to copy and orphan the node instead of passing it to the `DataTree` constructor.
Apparently this does not please `mypy` because while `DataTree` has a `copy` method, that is inherited from `Dataset`. The `copy` is only necessary because `orphan` works in-place (but then again you'd probably need `copy` to implement a side-effect free `orphan`).
For reference, I'm currently working around this limitation using
```python
import posixpath
def normalize_tree_dict(mapping):
def _normalize(mapping):
for path, item in …
```
> actually allow `DataTree` objects as values in `from_dict`

- datatree/__init__.py
- datatree/tests/test_datatree.py
- datatree/tests/test_treenode.py
- datatree/treenode.py
- docs/source/api.rst
- docs/source/whats-new.rst
Makes exception classes more specific by replacing `TreeError` with `InvalidTreeError` and `NotFoundInTreeError`.
> Improved exception types

- ci/doc.yml
- docs/Makefile
- docs/source/conf.py
- docs/source/whats-new.rst
Should fix the bug in the readthedocs build I'm seeing in #170, #171, #172.
Changing to match xarray's docs theme will also slightly streamline merging the docs upstream eventually.
> Use xarray docs theme instead of pangeo

- datatree/tests/test_treenode.py
- datatree/treenode.py
- docs/source/api.rst
- docs/source/whats-new.rst
Adds a `.descendants` property, which does the same thing as `.subtree` but doesn't return the current node.
Also added tests for several properties that were not explicitly tested before - `lineage`, `ancestors`, and `subtree`.
> Descendants property

- docs/source/index.rst
- docs/source/terminology.rst
- docs/source/whats-new.rst
Adds a page on terminology that should be integrated into [xarray's page on terminology](https://docs.xarray.dev/en/stable/user-guide/terminology.html).
> Terminology

- datatree/datatree.py
- datatree/tests/test_datatree.py
- docs/source/api.rst
- docs/source/whats-new.rst
I called it `drop_nodes` plural for consistency with `Dataset.drop_vars`.
> Added drop_nodes method

- datatree/datatree.py
- datatree/tests/test_datatree.py
- docs/source/whats-new.rst
> Fix name permanence behaviour in update method

- datatree/datatree.py
- datatree/ops.py
- datatree/tests/test_datatree.py
- docs/source/api.rst
- docs/source/whats-new.rst
> Add assign method

- docs/source/index.rst
- docs/source/whats-new.rst
> Add content to Index page

- datatree/datatree.py
- datatree/tests/test_datatree.py
- docs/source/api.rst
- docs/source/whats-new.rst
Method to filter nodes based on some condition
> Add filter method

- ci/doc.yml
- docs/source/conf.py
- docs/source/data-structures.rst
- docs/source/hierarchical-data.rst
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/io.rst
- docs/source/quick-overview.rst
- docs/source/terminology.rst
- docs/source/tutorial.rst
- docs/source/whats-new.rst
Attempt to fix broken code links in docs, specified by ``:py:class:`DataTree` ``
Doesn't work yet though, and I don't know why :confused:
> Try to fix code links in docs

- README.md
There's been a [breaking change](https://github.com/badges/shields/issues/8671) to the workflow badge routes, so we have to follow that. This also hard-codes the branch to `main`, which I think is more predictable than
> look […] for builds on the default branch and fall back to the latest build on any branch or ref if none are found on the default branch.
> update the badge route

- .github/workflows/main.yaml
- .github/workflows/pypipublish.yaml
- ci/doc.yml
- ci/environment.yml
- docs/source/whats-new.rst
- setup.cfg
> Deprecate python 3.8

- .github/workflows/main.yaml
- datatree/tests/test_treenode.py
- datatree/treenode.py
- docs/source/whats-new.rst
This fixes a subclassing issue with the NodePath class currently implemented in datatree. This also adds a test for the NodePath class, and adds tests for python 3.12. A check for python version is used to ensure backwards compatibility.
> FIX: Fix bug with nodepath python 3.12 issues

- datatree/mapping.py
- datatree/tests/test_datatree.py
- datatree/tests/test_mapping.py
- docs/source/whats-new.rst
Not totally sure if this is a good idea yet
> Map over only data nodes, ignoring attrs

- datatree/datatree.py
> Alternative fix for #188

- datatree/datatree.py
- datatree/mapping.py
- datatree/tests/test_mapping.py
- docs/source/whats-new.rst
Doing this because
a) It's safer to make the dataset passed to `map_over_subtree` immutable, so the user can't modify in-place,
b) It would allow adding the `.path` to the `DatasetView` object as suggested in #266.
> DatasetView in map_over_subtree

- datatree/datatree.py
- datatree/tests/test_datatree.py
- datatree/tests/test_formatting.py
- docs/source/api.rst
- docs/source/hierarchical-data.rst
- docs/source/whats-new.rst
> Method to match node paths via glob

- datatree/tests/__init__.py
- docs/source/whats-new.rst
- pyproject.toml
> Do not use the deprecated distutils

- datatree/datatree.py
- datatree/tests/test_datatree.py
- docs/source/api.rst
- docs/source/hierarchical-data.rst
- docs/source/whats-new.rst
Introduces the concept of a "hollow tree" - a tree which contains data only at the leaves. This is a codified name for a specific tree structure that a lot of users already intuitively create. Codifying it is useful because there are some operations (e.g. `reorder` - see https://github.com/xarray-contrib/datatree/pull/271) that don't make sense for non-hollow trees.
> is_hollow method

- datatree/datatree.py
- datatree/io.py
- datatree/tests/test_io.py
- docs/source/whats-new.rst
> Change default write mode of `to_zarr()` to `'w-'`

- datatree/mapping.py
- datatree/tests/test_mapping.py
- docs/source/whats-new.rst
> Keep attrs in `map_over_subtree`

- datatree/testing.py
- docs/source/whats-new.rst
- pyproject.toml
> Fix for xarray v2023.12.0

- .gitignore
- ci/doc.yml
- datatree/mapping.py
- docs/README.md
- docs/source/api.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/whats-new.rst
This issue aims to fix the build fail in #286 
Also, hopefully it can help facilitate the merging into the xarray repo (documentation alignment)
- ~~[x] Tests added~~
- ~~[x] New functions/methods are listed in `api.rst`~~
- ~~[x] Changes are summarized in `docs/source/whats-new.rst`~~
Related to the issue 
- Removed `numpydoc` CI dependency
- Added `pickleshare` CI dependency to fix warnings happening during `make html` locally, that could probably happen in the CI too
- Added a README.md describing how to build, clean and open the documentation
- Removed `DataTree.imag` and `DataTree.real`, they were raising warnings during `make html`
- Fixed the issue and pull extlinks with the new repo's URL
- Copy pasted **all** `napoleon_` prefixed configuration variables in `conf.py`, from xarray …
> Use napoleon instead of numpydoc (xarray doc alignment), and fixes

- docs/source/data-structures.rst
typo found while reading the docs
> doc typo: Update data-structures.rst

- .gitignore
- datatree/mapping.py
- datatree/tests/test_treenode.py
- datatree/treenode.py
- docs/source/api.rst
- docs/source/whats-new.rst
- Yes
- No
- No
- Reason: See https://github.com/xarray-contrib/datatree/pull/286#issuecomment-1837556861
- Renamed `test_lineage` to `test_parents`
- Rewrote `test_lineage` so that it tests that the `lineage` and  `parents` properties are equivalent
- Wrote `test_iter_lineage` to verify that `iter_lineage` and `iter_parents` yield the same results
- :warning: I had to add a `#type: ignore` comment
- `lineage` and `iter_lineage` removed (see open point (3))
- `parents` and `iter_parents` added 
- In section  "Deprecation"
> DataTree.lineage should be renamed to .parents

- docs/source/api.rst
> Add Pathlike methods to api docs

- docs/source/hierarchical-data.rst
This is a clone of #300 because I nuked my fork without thinking. 
Since I'm reading the docs and don't know sphinx very well, I saw a problem with the is_hollow description and fixed it.
It may make more sense to have Tree Contents: Hollow Trees above Manipulating Trees: Subsetting Tree Nodes, but the simpsons DataTree is undefined. Rather than create a new tree for this example I just moved it.
In addition to moving it I changed the description from a python method to the py:class so that the rendering didn't include the incorrect parens.
The updated docs after rebuilding show the tree is not hollow rather than NameError: name 'simpsons' is not defined as it did before
New image generated: 
Also increased clarity of the `dt.match()` operation by printing the result. 
And fixed a typo. …
> Moves Tree Contents so that simpsons data tree in example is defined.
